[package]
name = "frequency_domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.5"
ndarray = "0.15.6"
num = "0.4.1"
